variables:
  PYTORCH_IMAGE: registry.sensetime.com/openmmlab/pytorch18-cu102-mmcv-transforms:update-repo

stages:
  # - linting
  - test
  - deploy

before_script:
  - . /root/scripts/set_envs.sh
  - echo $PATH
  - gcc --version
  - nvcc --version
  - ruby --version
  - python --version
  - pip --version
  - python -c "import torch; print(torch.__version__)"
  - python -c "import mmcv; print(mmcv.__version__)"

linting:
  image: $PYTORCH_IMAGE
  stage: test
  script:
    - pre-commit run --all-files

.test_template: &test_template_def
  stage: test
  script:
    - echo "Configurating git..."
    - git config --local core.sshCommand "/usr/bin/ssh -i /root/.ssh/id_gitlab"
    - echo "Installing mmdet..."
    - git clone --branch refactor_dev -c core.sshCommand="/usr/bin/ssh -i /root/.ssh/id_gitlab" git@gitlab.sh.sensetime.com:openmmlab-enterprise/openmmlab-ce/mmdetection.git /mmdet
    # - pip install -e /mmdet -i https://pypi.tuna.tsinghua.edu.cn/simple/
    - pip install -e /mmdet
    - python -c "import mmdet; print(mmdet.__version__)"
    - echo "Installing mmcls..."
    - git clone --branch dev-1.x -c core.sshCommand="/usr/bin/ssh -i /root/.ssh/id_gitlab" git@gitlab.sh.sensetime.com:openmmlab-enterprise/openmmlab-ce/mmclassification.git /mmclassification
    # - pip install -e /mmdet -i https://pypi.tuna.tsinghua.edu.cn/simple/
    - pip install -e /mmclassification
    - python -c "import mmcls; print(mmcls.__version__)"
    - echo "Start building..."
    - pip install -e .[all]
    # - pip install -e .[all] -i https://pypi.tuna.tsinghua.edu.cn/simple/
    - pip install git+https://github.com/JonathonLuiten/TrackEval.git
    - pip install git+https://github.com/votchallenge/toolkit.git
    - pip install git+https://github.com/TAO-Dataset/tao.git
    - echo "Start testing..."
    - python -c "import mmtrack; print(mmtrack.__version__)"
    - pytest tests/
    # - coverage run --branch --source mmtrack -m pytest tests/
    # - coverage report -m
    # - interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-regex "__repr__" --fail-under 60

test:pytorch1.8-cuda10:
  image: $PYTORCH_IMAGE
  <<: *test_template_def
