version: 2.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  lint_only:
    type: boolean
    default: true

jobs:
  lint:
    docker:
      - image: cimg/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install pre-commit hook
          command: |
            pip install pre-commit
            pre-commit install
      - run:
          name: Linting
          command: pre-commit run --all-files
      - run:
          name: Check docstring coverage
          command: |
            pip install interrogate
            interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-magic --ignore-regex "__repr__" --fail-under 50 mmtrack
  build_cpu:
    parameters:
      # The python version must match available image tags in
      # https://circleci.com/developer/images/image/cimg/python
      python:
        type: string
        default: "3.7.4"
      torch:
        type: string
      torchvision:
        type: string
    docker:
      - image: cimg/python:<< parameters.python >>
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install Libraries
          command: |
            sudo apt-get update
            sudo apt-get install -y ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 libgl1-mesa-glx libjpeg-dev zlib1g-dev libtinfo-dev libncurses5
      - run:
          name: Configure Python & pip
          command: |
            python -m pip install --upgrade pip
            python -m pip install wheel
      - run:
          name: Install PyTorch
          command: |
            python -V
            python -m pip install torch==<< parameters.torch >>+cpu torchvision==<< parameters.torchvision >>+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - run:
          name: Install mmtrack dependencies
          command: |
            pip install -U openmim
            python -m pip install git+ssh://git@github.com/open-mmlab/mmengine.git@main
            mim install 'mmcv >= 2.0.0rc1'
            # TODO: fix bc-breaking from mmdet detr-refactor
            # python -m pip install git+ssh://git@github.com/open-mmlab/mmdetection.git@dev-3.x
            mim install 'mmdet == 3.0.0rc5'
            python -m pip install git+ssh://git@github.com/open-mmlab/mmclassification.git@dev-1.x
            python -m pip install -r requirements.txt
            python -m pip install git+https://github.com/JonathonLuiten/TrackEval.git
            python -m pip install git+https://github.com/votchallenge/toolkit.git
            python -m pip install git+https://github.com/TAO-Dataset/tao.git
      - run:
          name: Build and install
          command: |
            python -m pip install -e .
      - run:
          name: Run unittests
          command: |
            python -m coverage run --branch --source mmtrack -m pytest tests/
            python -m coverage xml
            python -m coverage report -m
  build_cuda:
    parameters:
      torch:
        type: string
      cuda:
        type: enum
        enum: ["10.1", "10.2", "11.1"]
      cudnn:
        type: integer
        default: 7
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
      # docker_layer_caching: true
    resource_class: gpu.nvidia.small
    steps:
      - checkout
      - run:
          # CLoning repos in VM since Docker doesn't have access to the private key
          name: Clone Repos
          command: |
            git clone -b main --depth 1 ssh://git@github.com/open-mmlab/mmengine.git /home/circleci/mmengine
            git clone -b dev-3.x --depth 1 ssh://git@github.com/open-mmlab/mmdetection.git /home/circleci/mmdetection
            git clone -b dev-1.x --depth 1 ssh://git@github.com/open-mmlab/mmclassification.git /home/circleci/mmclassification
      - run:
          name: Build Docker image
          command: |
            docker build .circleci/docker -t mmtrack:gpu --build-arg PYTORCH=<< parameters.torch >> --build-arg CUDA=<< parameters.cuda >> --build-arg CUDNN=<< parameters.cudnn >>
            docker run --gpus all -t -d -v /home/circleci/project:/mmtrack -v /home/circleci/mmengine:/mmengine -v /home/circleci/mmdetection:/mmdetection -v /home/circleci/mmclassification:/mmclassification -w /mmtrack --name mmtrack mmtrack:gpu
      - run:
          name: Install mmtrack dependencies
          command: |
            docker exec mmtrack apt-get -y install git
            docker exec mmtrack pip install -e /mmengine
            docker exec mmtrack pip install -U openmim
            docker exec mmtrack mim install 'mmcv >= 2.0.0rc1'
            # TODO: fix bc-breaking from mmdet detr-refactor
            # docker exec mmtrack pip install -e /mmdetection
            docker exec mmtrack mim install 'mmdet == 3.0.0rc5'
            docker exec mmtrack pip install -e /mmclassification
            docker exec mmtrack pip install -r requirements.txt
            docker exec mmtrack python -m pip install git+https://github.com/JonathonLuiten/TrackEval.git
            docker exec mmtrack python -m pip install git+https://github.com/votchallenge/toolkit.git
            docker exec mmtrack python -m pip install git+https://github.com/TAO-Dataset/tao.git
      - run:
          name: Build and install
          command: |
            docker exec mmtrack pip install -e .
      - run:
          name: Run unittests
          command: |
            docker exec mmtrack python -m pytest tests/
workflows:
  pr_stage_lint:
    when: << pipeline.parameters.lint_only >>
    jobs:
      - lint:
          name: lint
          filters:
            branches:
              ignore:
                - dev-1.x
  pr_stage_test:
    when:
      not:
        << pipeline.parameters.lint_only >>
    jobs:
      - lint:
          name: lint
          filters:
            branches:
              ignore:
                - dev-1.x
      - build_cpu:
          name: minimum_version_cpu
          torch: 1.7.0
          torchvision: 0.8.1
          python: 3.7.4  # The lowest python 3.7.x version available on CircleCI images
          requires:
            - lint
      - build_cpu:
          name: maximum_version_cpu
          torch: 1.13.0
          torchvision: 0.14.0
          python: 3.9.0
          requires:
            - minimum_version_cpu
      - hold:
          type: approval
          requires:
            - maximum_version_cpu
      - build_cuda:
          name: mainstream_version_gpu
          torch: 1.8.1
          # Use double quotation mark to explicitly specify its type
          # as string instead of number
          cuda: "10.2"
          requires:
            - hold
  merge_stage_test:
    when:
      not:
        << pipeline.parameters.lint_only >>
    jobs:
      - build_cuda:
          name: mainstream_version_gpu
          torch: 1.8.1
          # Use double quotation mark to explicitly specify its type
          # as string instead of number
          cuda: "10.2"
          filters:
            branches:
              only:
                - dev-1.x
