Collections:
  - Name: FGFA
    Metadata:
      Training Data: ImageNet DET, ImageNet VID
      Training Techniques:
        - SGD with Momentum
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
        URL: https://arxiv.org/abs/1703.10025
        Title: Flow-Guided Feature Aggregation for Video Object Detection
    README: configs/vid/fgfa/README.md

Models:
  - Name: fgfa_faster_rcnn_r50_dc5_1x_imagenetvid
    In Collection: FGFA
    Config: configs/vid/fgfa/fgfa_faster_rcnn_r50_dc5_1x_imagenetvid.py
    Metadata:
      Training Memory (GB): 4.10
    Results:
      - Task: Video Object Detection
        Dataset: ImageNet VID
        Metrics:
          box AP@0.5: 74.7
    Weights: https://download.openmmlab.com/mmtracking/vid/fgfa/fgfa_faster_rcnn_r50_dc5_1x_imagenetvid/fgfa_faster_rcnn_r50_dc5_1x_imagenetvid_20201228_022657-f42016f3.pth

  - Name: fgfa_faster_rcnn_r101_dc5_1x_imagenetvid
    In Collection: FGFA
    Config: configs/vid/fgfa/fgfa_faster_rcnn_r101_dc5_1x_imagenetvid.py
    Metadata:
      Training Memory (GB): 5.80
    Results:
      - Task: Video Object Detection
        Dataset: ImageNet VID
        Metrics:
          box AP@0.5: 77.8
    Weights: https://download.openmmlab.com/mmtracking/vid/fgfa/fgfa_faster_rcnn_r101_dc5_1x_imagenetvid/fgfa_faster_rcnn_r101_dc5_1x_imagenetvid_20201219_011831-9c9d8183.pth

  - Name: fgfa_faster_rcnn_x101_dc5_1x_imagenetvid
    In Collection: FGFA
    Config: configs/vid/fgfa/fgfa_faster_rcnn_x101_dc5_1x_imagenetvid.py
    Metadata:
      Training Memory (GB): 9.74
    Results:
      - Task: Video Object Detection
        Dataset: ImageNet VID
        Metrics:
          box AP@0.5: 79.6
    Weights: https://download.openmmlab.com/mmtracking/vid/fgfa/fgfa_faster_rcnn_x101_dc5_1x_imagenetvid/fgfa_faster_rcnn_x101_dc5_1x_imagenetvid_20210818_223334-8723c594.pth
