Collections:
  - Name: FP16
    Metadata:
      Training Techniques:
        - Mixed Precision Training
      Training Resources: 8x TITAN Xp GPUs
    Paper:
        URL: https://arxiv.org/abs/1710.03740
        Title: Mixed Precision Training
    README: configs/mot/tracktor/fp16/README.md

Models:
  - Name: tracktor_faster-rcnn_r50_fpn_fp16_4e_mot17-private-half
    In Collection: FP16
    Config: configs/mot/tracktor/fp16/tracktor_faster-rcnn_r50_fpn_fp16_4e_mot17-private-half.py
    Metadata:
      Training Data: MOT17-half-train
    Results:
      - Task: Multiple Object Tracking
        Dataset: MOT17-half-val
        Metrics:
          MOTA: 64.7
          IDF1: 66.6
    Weights:
      - https://download.openmmlab.com/mmtracking/fp16/faster-rcnn_r50_fpn_fp16_4e_mot17-half_20210730_002436-f4ba7d61.pth
      - https://download.openmmlab.com/mmtracking/fp16/reid_r50_fp16_8x32_6e_mot17_20210731_033055-4747ee95.pth
