Collections:
  - Name: FP16
    Metadata:
      Training Techniques:
        - Mixed Precision Training
      Training Resources: 8x TITAN Xp GPUs
    Paper:
        URL: https://arxiv.org/abs/1710.03740
        Title: Mixed Precision Training
    README: configs/sot/siamese_rpn/fp16/README.md

Models:
  - Name: siamese_rpn_r50_fp16_1x_lasot
    In Collection: FP16
    Config: configs/sot/siamese_rpn/fp16/siamese_rpn_r50_fp16_1x_lasot.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): 7.54
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: LaSOT
        Metrics:
          Success: 49.1
          Norm precision: 57.0
    Weights: https://download.openmmlab.com/mmtracking/fp16/siamese_rpn_r50_fp16_1x_lasot_20210731_110245-6733c67e.pth
