Collections:
  - Name: SiameseRPN++
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Techniques:
        - SGD with Momentum
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
        URL: https://arxiv.org/abs/1812.11703
        Title: SiamRPN++ Evolution of Siamese Visual Tracking with Very Deep Networks
    README: configs/sot/siamese_rpn/README.md

Models:
  - Name: siamese_rpn_r50_1x_lasot
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_1x_lasot.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): 7.54
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: LaSOT
        Metrics:
          Success: 50.1
          Norm precision: 59.1
          Precision: 48.7
    Weights: https://download.openmmlab.com/mmtracking/sot/siamese_rpn/siamese_rpn_r50_1x_lasot/siamese_rpn_r50_1x_lasot_20211203_151612-da4b3c66.pth

  - Name: siamese_rpn_r50_1x_uav123
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_1x_uav123.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): 7.54
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: UAV123
        Metrics:
          Success: 59.8
          Norm precision: 77.3
          Precision: 80.0
    Weights: https://download.openmmlab.com/mmtracking/sot/siamese_rpn/siamese_rpn_r50_1x_uav123/siamese_rpn_r50_1x_uav123_20211203_153949-6d82f39e.pth

  - Name: siamese_rpn_r50_1x_trackingnet
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_1x_trackingnet.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): 7.54
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: TrackingNet
        Metrics:
          Success: 69.0
          Norm precision: 75.8
          Precision: 63.2
    Weights: https://download.openmmlab.com/mmtracking/sot/siamese_rpn/siamese_rpn_r50_1x_lasot/siamese_rpn_r50_1x_lasot_20211203_151612-da4b3c66.pth

  - Name: siamese_rpn_r50_1x_otb100
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_1x_otb100.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): _
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: OTB100
        Metrics:
          Success: 65.1
          Norm precision: 82.0
          Precision: 86.1
    Weights: https://download.openmmlab.com/mmtracking/sot/siamese_rpn/siamese_rpn_r50_1x_otb100/siamese_rpn_r50_1x_otb100_20211203_154048-9dfde4fa.pth

  - Name: siamese_rpn_r50_1x_vot2018
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_1x_vot2018.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): _
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: VOT2018
        Metrics:
          EAO: 0.348
          Accuracy: 0.578
          Robustness: 0.272
    Weights: https://download.openmmlab.com/mmtracking/sot/siamese_rpn/siamese_rpn_r50_1x_vot2018/siamese_rpn_r50_1x_vot2018_20211206_211710-10e082cd.pth

  - Name: siamese_rpn_r50_fp16_1x_lasot
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_fp16_1x_lasot.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): 7.54
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: LaSOT
        Metrics:
          Success: 49.1
          Norm precision: 57.0
    Weights: https://download.openmmlab.com/mmtracking/fp16/siamese_rpn_r50_fp16_1x_lasot_20210731_110245-6733c67e.pth
