Collections:
  - Name: SiameseRPN++
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Techniques:
        - SGD with Momentum
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
        URL: https://arxiv.org/abs/1812.11703
        Title: SiamRPN++ Evolution of Siamese Visual Tracking with Very Deep Networks
    README: configs/sot/siamese_rpn/README.md

Models:
  - Name: siamese_rpn_r50_20e_lasot
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_20e_lasot.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): 7.54
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: LaSOT
        Metrics:
          Success: 50.4
          Norm precision: 59.6
          Precision: 49.7
    Weights: https://download.openmmlab.com/mmtracking/sot/siamese_rpn/siamese_rpn_r50_1x_lasot/siamese_rpn_r50_20e_lasot_20220420_181845-dd0f151e.pth

  - Name: siamese_rpn_r50_20e_uav123
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_20e_uav123.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): 7.54
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: UAV123
        Metrics:
          Success: 60
          Norm precision: 77.3
          Precision: 80.3
    Weights: https://download.openmmlab.com/mmtracking/sot/siamese_rpn/siamese_rpn_r50_1x_uav123/siamese_rpn_r50_20e_uav123_20220420_181845-dc2d4831.pth

  - Name: siamese_rpn_r50_20e_trackingnet
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_20e_trackingnet.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): 7.54
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: TrackingNet
        Metrics:
          Success: 68.8
          Norm precision: 75.9
          Precision: 63.2
    Weights: https://download.openmmlab.com/mmtracking/sot/siamese_rpn/siamese_rpn_r50_1x_lasot/siamese_rpn_r50_20e_lasot_20220420_181845-dd0f151e.pth

  - Name: siamese_rpn_r50_20e_otb100
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_20e_otb100.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): _
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: OTB100
        Metrics:
          Success: 64.9
          Norm precision: 82.4
          Precision: 86.3
    Weights: https://download.openmmlab.com/mmtracking/sot/siamese_rpn/siamese_rpn_r50_1x_otb100/siamese_rpn_r50_20e_otb100_20220421_144232-6b8f1730.pth

  - Name: siamese_rpn_r50_20e_vot2018
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_20e_vot2018.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): _
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: VOT2018
        Metrics:
          EAO: 0.348
          Accuracy: 0.588
          Robustness: 0.295
    Weights: https://download.openmmlab.com/mmtracking/sot/siamese_rpn/siamese_rpn_r50_1x_vot2018/siamese_rpn_r50_20e_vot2018_20220420_181845-1111f25e.pth

  - Name: siamese_rpn_r50_fp16_20e_lasot
    In Collection: SiameseRPN++
    Config: configs/sot/siamese_rpn/siamese_rpn_r50_fp16_20e_lasot.py
    Metadata:
      Training Data: MSCOCO, ImageNet DET, ImageNet VID
      Training Memory (GB): 7.54
      Epochs: 20
    Results:
      - Task: Single Object Tracking
        Dataset: LaSOT
        Metrics:
          Success: 50.4
          Norm precision: 59.6
          Precision: 49.2
    Weights: https://download.openmmlab.com/mmtracking/fp16/siamese_rpn_r50_fp16_20e_lasot_20220422_181501-ce30fdfd.pth
