Collections:
  - Name: DFF
    Metadata:
      Training Data: ILSVRC
      Training Techniques:
        - SGD with Momentum
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper: https://arxiv.org/abs/1611.07715
    README: configs/vid/dff/README.md

Models:
  - Name: dff_faster_rcnn_r50_dc5_1x_imagenetvid
    In Collection: DFF
    Config: configs/vid/dff/dff_faster_rcnn_r50_dc5_1x_imagenetvid.py
    Metadata:
      Training Memory (GB): 2.50
    Results:
      - Task: Video Object Detection
        Dataset: ILSVRC
        Metrics:
          box AP@0.5: 70.3
    Weights: https://download.openmmlab.com/mmtracking/vid/dff/dff_faster_rcnn_r50_dc5_1x_imagenetvid/dff_faster_rcnn_r50_dc5_1x_imagenetvid_20201227_213250-548911a4.pth

  - Name: dff_faster_rcnn_r101_dc5_1x_imagenetvid
    In Collection: DFF
    Config: configs/vid/dff/dff_faster_rcnn_r101_dc5_1x_imagenetvid.py
    Metadata:
      Training Memory (GB): 3.25
    Results:
      - Task: Video Object Detection
        Dataset: ILSVRC
        Metrics:
          box AP@0.5: 73.5
    Weights: https://download.openmmlab.com/mmtracking/vid/dff/dff_faster_rcnn_r101_dc5_1x_imagenetvid/dff_faster_rcnn_r101_dc5_1x_imagenetvid_20201218_172720-ad732e17.pth
