Collections:
  - Name: FP16
    Metadata:
      Training Techniques:
        - Mixed Precision Training
      Training Resources: 8x TITAN Xp GPUs
    Paper:
        URL: https://arxiv.org/abs/1710.03740
        Title: Mixed Precision Training
    README: configs/vid/selsa/fp16/README.md

Models:
  - Name: selsa_faster_rcnn_r50_dc5_fp16_1x_imagenetvid
    In Collection: FP16
    Config: configs/vid/selsa/fp16/selsa_faster_rcnn_r50_dc5_fp16_1x_imagenetvid.py
    Metadata:
      Training Data: ImageNet DET, ImageNet VID
      Training Memory (GB): 2.71
      Epochs: 7
    Results:
      - Task: Video Object Detection
        Dataset: ImageNet VID
        Metrics:
          box AP@0.5: 78.7
    Weights: https://download.openmmlab.com/mmtracking/fp16/selsa_faster_rcnn_r50_dc5_fp16_1x_imagenetvid_20210728_193846-dce6eb09.pth
