Collections:
  - Name: SELSA
    Metadata:
      Training Data: ImageNet DET, ImageNet VID
      Training Techniques:
        - SGD with Momentum
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
        URL: https://arxiv.org/abs/1907.06390
        Title: Sequence Level Semantics Aggregation for Video Object Detection
    README: configs/vid/selsa/README.md

Models:
  - Name: selsa_faster_rcnn_r50_dc5_1x_imagenetvid
    In Collection: SELSA
    Config: configs/vid/selsa/selsa_faster_rcnn_r50_dc5_1x_imagenetvid.py
    Metadata:
      Training Memory (GB): 3.49
    Results:
      - Task: Video Object Detection
        Dataset: ImageNet VID
        Metrics:
          box AP@0.5: 78.4
    Weights: https://download.openmmlab.com/mmtracking/vid/selsa/selsa_faster_rcnn_r50_dc5_1x_imagenetvid/selsa_faster_rcnn_r50_dc5_1x_imagenetvid_20201227_204835-2f5a4952.pth

  - Name: selsa_faster_rcnn_r101_dc5_1x_imagenetvid
    In Collection: SELSA
    Config: configs/vid/selsa/selsa_faster_rcnn_r101_dc5_1x_imagenetvid.py
    Metadata:
      Training Memory (GB): 5.18
    Results:
      - Task: Video Object Detection
        Dataset: ImageNet VID
        Metrics:
          box AP@0.5: 81.5
    Weights: https://download.openmmlab.com/mmtracking/vid/selsa/selsa_faster_rcnn_r101_dc5_1x_imagenetvid/selsa_faster_rcnn_r101_dc5_1x_imagenetvid_20201218_172724-aa961bcc.pth

  - Name: selsa_faster_rcnn_x101_dc5_1x_imagenetvid
    In Collection: SELSA
    Config: configs/vid/selsa/selsa_faster_rcnn_x101_dc5_1x_imagenetvid.py
    Metadata:
      Training Memory (GB): 9.15
    Results:
      - Task: Video Object Detection
        Dataset: ImageNet VID
        Metrics:
          box AP@0.5: 83.1
    Weights: https://download.openmmlab.com/mmtracking/vid/selsa/selsa_faster_rcnn_x101_dc5_1x_imagenetvid/selsa_faster_rcnn_x101_dc5_1x_imagenetvid_20210825_205641-10252965.pth

  - Name: selsa_faster_rcnn_r50_dc5_fp16_1x_imagenetvid
    In Collection: SELSA
    Config: configs/vid/selsa/selsa_faster_rcnn_r50_dc5_fp16_1x_imagenetvid.py
    Metadata:
      Training Data: ImageNet DET, ImageNet VID
      Training Memory (GB): 2.71
      Epochs: 7
    Results:
      - Task: Video Object Detection
        Dataset: ImageNet VID
        Metrics:
          box AP@0.5: 78.7
    Weights: https://download.openmmlab.com/mmtracking/fp16/selsa_faster_rcnn_r50_dc5_fp16_1x_imagenetvid_20210728_193846-dce6eb09.pth
