Collections:
  - Name: SELSA
    Metadata:
      Training Data: ILSVRC
      Training Techniques:
        - SGD with Momentum
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper: https://arxiv.org/abs/1907.06390
    README: configs/vid/selsa/README.md

Models:
  - Name: selsa_faster_rcnn_r50_dc5_1x_imagenetvid
    In Collection: SELSA
    Config: configs/vid/selsa/selsa_faster_rcnn_r50_dc5_1x_imagenetvid.py
    Metadata:
      Training Memory (GB): 3.49
    Results:
      - Task: Video Object Detection
        Dataset: ILSVRC
        Metrics:
          box AP@0.5: 78.4
    Weights: https://download.openmmlab.com/mmtracking/vid/selsa/selsa_faster_rcnn_r50_dc5_1x_imagenetvid/selsa_faster_rcnn_r50_dc5_1x_imagenetvid_20201227_204835-2f5a4952.pth

  - Name: selsa_faster_rcnn_r101_dc5_1x_imagenetvid
    In Collection: SELSA
    Config: configs/vid/selsa/selsa_faster_rcnn_r101_dc5_1x_imagenetvid.py
    Metadata:
      Training Memory (GB): 5.18
    Results:
      - Task: Video Object Detection
        Dataset: ILSVRC
        Metrics:
          box AP@0.5: 81.5
    Weights: https://download.openmmlab.com/mmtracking/vid/selsa/selsa_faster_rcnn_r101_dc5_1x_imagenetvid/selsa_faster_rcnn_r101_dc5_1x_imagenetvid_20201218_172724-aa961bcc.pth
